version: "3.6"

services:
  item:
    build:
      context: "."
      dockerfile: "./item/app.dockerfile"
    depends_on:
      - "item_db"
    environment:
      DATABASE_URL: "postgres://postgres:takewaka@item_db:grpcproto?sslmode=disable&port=5432"

  item_db:
    build:
      context: "./item"
      dockerfile: "./db.dockerfile"
    environment:
      POSTGRES_DB: "grpcproto"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "takewaka"
    restart: "unless-stopped"
