version: "3.6"

services:
  item:
    build:
      context: "."
      dockerfile: "./item/app.dockerfile"
    depends_on:
      - "item_db"
    environment:
      DATABASE_URL: "postgres://takewaka:takewaka@item_db/grpcproto?sslmode=disable"

  item_db:
    build:
      context: "./item"
      dockerfile: "./db.dockerfile"
    environment:
      POSTGRES_DB: "grpcproto"
      POSTGRES_USER: "takewaka"
      POSTGRES_PASSWORD: "takewaka"
    restart: "unless-stopped"

  user:
    build:
      context: "."
      dockerfile: "./user/app.dockerfile"
    depends_on:
      - "user_db"
    environment:
      DATABASE_URL: "postgres://takewaka:takewaka@user_db/grpcproto?sslmode=disable"

  user_db:
    build:
      context: "./user"
      dockerfile: "./db.dockerfile"
    environment:
      POSTGRES_DB: "grpcproto"
      POSTGRES_USER: "takewaka"
      POSTGRES_PASSWORD: "takewaka"
    restart: "unless-stopped"

  coordinate:
    build:
      context: "."
      dockerfile: "./coordinate/app.dockerfile"
    depends_on:
      - "coordinate_db"
      - "item"
      - "user"
    environment:
      DATABASE_URL: "postgres://takewaka:takewaka@coordinate_db/grpcproto?sslmode=disable"
      ITEM_URL: "item:8080"
      USER_URL: "user:8080"

  coordinate_db:
    build:
      context: "./coordinate"
      dockerfile: "./db.dockerfile"
    environment:
      POSTGRES_DB: "grpcproto"
      POSTGRES_USER: "takewaka"
      POSTGRES_PASSWORD: "takewaka"
    restart: "unless-stopped"

  client:
    build:
      context: "."
      dockerfile: "./cli/cli.dockerfile"
    depends_on:
      - "item"
      - "user"
    environment:
      ITEM_URL: "item:8080"
      USER_URL: "user:8080"
      COORDINATE_URL: "coordinate:8080"
