// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_06475274529c307a, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetUserRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_06475274529c307a, []int{1}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_06475274529c307a, []int{2}
}
func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(dst, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUsersRequest struct {
	Skip                 int32    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take                 int32    `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_06475274529c307a, []int{3}
}
func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (dst *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(dst, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

func (m *GetUsersRequest) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetUsersRequest) GetTake() int32 {
	if m != nil {
		return m.Take
	}
	return 0
}

type GetUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_06475274529c307a, []int{4}
}
func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (dst *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(dst, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type PostUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostUserRequest) Reset()         { *m = PostUserRequest{} }
func (m *PostUserRequest) String() string { return proto.CompactTextString(m) }
func (*PostUserRequest) ProtoMessage()    {}
func (*PostUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_06475274529c307a, []int{5}
}
func (m *PostUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostUserRequest.Unmarshal(m, b)
}
func (m *PostUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostUserRequest.Marshal(b, m, deterministic)
}
func (dst *PostUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostUserRequest.Merge(dst, src)
}
func (m *PostUserRequest) XXX_Size() int {
	return xxx_messageInfo_PostUserRequest.Size(m)
}
func (m *PostUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostUserRequest proto.InternalMessageInfo

func (m *PostUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PostUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostUserResponse) Reset()         { *m = PostUserResponse{} }
func (m *PostUserResponse) String() string { return proto.CompactTextString(m) }
func (*PostUserResponse) ProtoMessage()    {}
func (*PostUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_06475274529c307a, []int{6}
}
func (m *PostUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostUserResponse.Unmarshal(m, b)
}
func (m *PostUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostUserResponse.Marshal(b, m, deterministic)
}
func (dst *PostUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostUserResponse.Merge(dst, src)
}
func (m *PostUserResponse) XXX_Size() int {
	return xxx_messageInfo_PostUserResponse.Size(m)
}
func (m *PostUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostUserResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*GetUserRequest)(nil), "pb.getUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "pb.getUserResponse")
	proto.RegisterType((*GetUsersRequest)(nil), "pb.getUsersRequest")
	proto.RegisterType((*GetUsersResponse)(nil), "pb.getUsersResponse")
	proto.RegisterType((*PostUserRequest)(nil), "pb.postUserRequest")
	proto.RegisterType((*PostUserResponse)(nil), "pb.postUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	PostUser(ctx context.Context, in *PostUserRequest, opts ...grpc.CallOption) (*PostUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/pb.UserService/getUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/pb.UserService/getUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) PostUser(ctx context.Context, in *PostUserRequest, opts ...grpc.CallOption) (*PostUserResponse, error) {
	out := new(PostUserResponse)
	err := c.cc.Invoke(ctx, "/pb.UserService/postUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	PostUser(context.Context, *PostUserRequest) (*PostUserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_PostUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).PostUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UserService/PostUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).PostUser(ctx, req.(*PostUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "getUsers",
			Handler:    _UserService_GetUsers_Handler,
		},
		{
			MethodName: "postUser",
			Handler:    _UserService_PostUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_06475274529c307a) }

var fileDescriptor_user_06475274529c307a = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0x5d, 0x4a, 0xc3, 0x40,
	0x10, 0xee, 0xc6, 0x44, 0xeb, 0x14, 0xda, 0x32, 0xfa, 0x10, 0x8a, 0x48, 0x18, 0x10, 0x8a, 0x0f,
	0x11, 0xa2, 0x20, 0x5e, 0x23, 0xe2, 0x01, 0x1a, 0x3b, 0x48, 0x28, 0x36, 0x6b, 0x26, 0xf5, 0x66,
	0xde, 0x4f, 0x76, 0x37, 0xdb, 0x64, 0xf3, 0x36, 0x7c, 0xf9, 0x7e, 0xb3, 0x00, 0x27, 0xe1, 0x36,
	0xd7, 0x6d, 0xd3, 0x35, 0x18, 0xe9, 0x8a, 0x1e, 0x21, 0xfe, 0x10, 0x6e, 0x71, 0x09, 0x51, 0xbd,
	0x4f, 0x55, 0xa6, 0xb6, 0x49, 0x19, 0xd5, 0x7b, 0x44, 0x88, 0x8f, 0xbb, 0x6f, 0x4e, 0xa3, 0x4c,
	0x6d, 0xaf, 0x4b, 0x7b, 0x53, 0x06, 0xcb, 0x2f, 0xee, 0x0c, 0xbd, 0xe4, 0x9f, 0x13, 0x4b, 0x37,
	0x55, 0xd1, 0x13, 0xac, 0xce, 0x0c, 0xd1, 0xcd, 0x51, 0x18, 0xef, 0x20, 0x36, 0x91, 0x96, 0xb4,
	0x28, 0xe6, 0xb9, 0xae, 0x72, 0xfb, 0xdd, 0xa2, 0xf4, 0x76, 0x16, 0x88, 0xf7, 0x44, 0x88, 0xe5,
	0x50, 0xeb, 0xde, 0xd5, 0xde, 0x06, 0xeb, 0x76, 0x07, 0xd7, 0x26, 0x29, 0xed, 0x4d, 0x05, 0xac,
	0x07, 0x69, 0x1f, 0x76, 0x0f, 0x89, 0xb1, 0x95, 0x54, 0x65, 0x17, 0x41, 0x9a, 0x83, 0xe9, 0x01,
	0x56, 0xba, 0x91, 0x60, 0x82, 0x1f, 0xaa, 0x46, 0x43, 0x11, 0xd6, 0x03, 0xcd, 0x59, 0x17, 0x7f,
	0x0a, 0x16, 0x06, 0x78, 0xe7, 0xf6, 0xb7, 0xfe, 0x64, 0x7c, 0x81, 0xab, 0x3e, 0x1e, 0xd1, 0xc4,
	0x84, 0x7f, 0x66, 0x73, 0x13, 0x60, 0xce, 0x83, 0x66, 0xf8, 0x0a, 0x73, 0x5f, 0x1a, 0xc7, 0x14,
	0xbf, 0x7e, 0x73, 0x1b, 0x82, 0x63, 0xa1, 0xaf, 0xe4, 0x84, 0x93, 0x1d, 0x4e, 0x38, 0x6d, 0x4d,
	0xb3, 0xea, 0xd2, 0xbe, 0xf5, 0xf3, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x09, 0x73, 0xe5,
	0xf9, 0x01, 0x00, 0x00,
}
